# Generated by Django 2.1 on 2018-08-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitapAdi', models.CharField(max_length=150, verbose_name='Kitaplar')),
                ('yaazarAdi', models.CharField(max_length=150, verbose_name='Yazarlar')),
                ('yayineviAdi', models.CharField(max_length=150, verbose_name='YayınEvleri')),
            ],
        ),
    ]
