# Generated by Django 2.1 on 2018-08-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_kitaps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yayınevi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yayinevi', models.CharField(max_length=150, verbose_name='yayinevi')),
            ],
        ),
    ]
