# Generated by Django 2.1 on 2018-08-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_yayınevi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Yayınevi',
            new_name='Yayinevi',
        ),
    ]
