# Generated by Django 2.1 on 2018-08-25 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20180825_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitaps',
            name='yayineviAdi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Yayinevi'),
        ),
    ]
